version: 2.1

workflows:
  build_and_test:
    jobs:
      - build:
          requires:
            - test
      - test

jobs:
  build:
    docker:
      - image: circleci/python:3.8

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Build Docker Image
          command: |
            docker build -t parisnk/$IMAGE_NAME:$CIRCLE_BUILD_NUM . -f .docker/Dockerfile

      - deploy:
          name: Push docker image
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push parisnk/$IMAGE_NAME:$CIRCLE_BUILD_NUM

  test:
    docker:
      - image: circleci/python:3.8

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Build Docker pytest image
          command: |
            docker build -t unittest . -f .docker/Unittest/Dockerfile
            docker run --rm unittest
