version: 2.1

workflows:
  build_and_test:
    jobs:
      - build
      # - test:
      #   requires:
      #     - build
      #   filters:
      #     branches:
      #       ignore: master
jobs:
  build:
    docker:
      - image: circleci/python:3.8

    steps:
      - checkout

      - setup_remote_docker
      #     docker_layer_caching: true

      - run:
          name: Build Docker Image
          command: |
            docker build -t parisnk/$IMAGE_NAME:$CIRCLE_BUILD_NUM .

      - deploy:
          name: Push docker image
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push parisnk/$IMAGE_NAME:$CIRCLE_BUILD_NUM
