version: 2.1

workflows:
  build_and_test:
    jobs:
      - build
      # - test:
      #   requires:
      #     - build
      #   filters:
      #     branches:
      #       ignore: master
jobs:
  build:
    docker:
      - image: docker:18.06.3-ce-git

        auth:
          username: parisnk
          password: $DOCKERHUB_PASSWORD

        environment:
          IMAGE_NAME: component-authentication

    steps:
      - checkout
      # - setup_remote_docker:
      # docker_layer_caching: true
      - add_ssh_keys

      - run:
          name: Build Docker Image
          command: |
            docker build -t "${DOCKER_USER}/${IMAGE_NAME}:${CIRCLE_SHA1}" .

      - deploy:
          name: Push docker image
          command: |
            echo "${DOCKER_PASS}" | docker login --username ${DOCKER_USER} --password-stdin
            docker push "${DOCKER_USER}/${IMAGE_NAME}:${CIRCLE_SHA1}"
