version: 2.1

workflows:
  build_and_test:
    jobs:
      - build
      # - test:
      #   requires:
      #     - build
      #   filters:
      #     branches:
      #       ignore: master
jobs:
  build:
    working_directory: ~/
    docker:
      - image: docker:python:3.8
      environment:
        IMAGE_NAME: component-authentication

    steps:
      - checkout
      # - setup_remote_docker:
      # docker_layer_caching: true
      - add_ssh_keys

      - run:
          name: Build Docker Image
          command: |
            docker build -t "${DOCKERHUB_USERNAME}/${IMAGE_NAME}:${CIRCLE_SHA1}" .

      - deploy:
          name: Push docker image
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login --username ${DOCKERHUB_USERNAME} --password-stdin
            docker push "${DOCKERHUB_USERNAME}/${IMAGE_NAME}:${CIRCLE_SHA1}"
